name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Public Repo
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git remote add public https://Graphomaniac:${PUBLIC_REPO_TOKEN}@github.com/mgsa-uoft/website.git
          git push public main:main --force
